
spring:
  datasource:
    url: jdbc:mysql://101.99.6.31:2206/sqa6?createDatabaseIfNotExist=true
    username: ltm
    password: Aladin@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
server:
  port: 8080